
project:
  name: JDBCSpringBootApp

server:
  port: 8080

spring:
  application:
    name: ${project.name}
  datasource:
    hikari:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://localhost;
      username: SA
      password: Password#1
  profiles:
    active: dev
  #added 171222
  jpa:
    open-in-view: false
# added spring.profiles.active=dev

swagger:
  use: true
  config:
    basePackage: "com.example.jdbcspringbootapp"
    appName: "AndreW_"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enabled: false
  endpoint:
    health:
      show-components: always
      show-details: always
  health:
    db:
      enabled: false

#logging:
#  config: classpath:logback/logback.xml
#  level:
#    com.example.jdbcspringbootapp: trace

service-settings:
  maxPagingRows: 20